name: simple cice pipeline

on:
  workflow_call:
    inputs:
      pullimage:
        required: false
        type: boolean
        default: false
      tagimage:
        required: false
        type: boolean
        default: false
      pushimage:
        required: false
        type: boolean
        default: false

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  docker_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Pull nginx image
        if: ${{ inputs.pullimage }}
        run: docker pull nginx

      - name: Tag image
        if: ${{ inputs.tagimage }}
        run: docker tag nginx:latest 851725608526.dkr.ecr.ap-south-1.amazonaws.com/coolakash:latest

      - name: Configure AWS credentials
        if: ${{ inputs.pushimage }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to ECR
        if: ${{ inputs.pushimage }}
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 123456789012.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push image
        if: ${{ inputs.pushimage }}
        run: docker push 851725608526.dkr.ecr.ap-south-1.amazonaws.com/coolakash:latest
